### USUARIOS
GET http://localhost:3000/users

### REGISTER
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Carol-Administradora",
    "email": "caroladm@pucminas.br",
    "phoneNumber": "31983614979",
    "password": "TesteCarol",
    "role": "admin"
}

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "caroladm@pucminas.br",
    "password": "TesteCarol"
}

### DELETE 
DELETE http://localhost:3000/users/




